name: ccmaarchive
services:
    app:
        build: .
        ports:
        - 8080:8080
        links:
        - postgres
        depends_on:
            postgres:
                condition: service_healthy
        restart: always
    postgres:
        build:
            context: .
            dockerfile: Dockerfile-postgres
        ports:
        - 5432:5432
        volumes:
        - ccmaarchive_database:/var/lib/postgresql/data
        environment:
        - POSTGRES_PASSWORD=changeit
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
volumes:
    ccmaarchive_database:
        external: true
